//! Tray icon + menu (macOS menu bar). The launcher runs menubar-only:
//! no Dock icon, window hides instead of closing, quit only from the tray.
//! Engine-related items reflect the live engine phase (refresh()).
//! Every item carries a native macOS template glyph (IconMenuItem), and the
//! menu intentionally omits force-restart / update-harness items — those are
//! covered by the Control Panel and engine card.
use tauri::menu::{IconMenuItem, IsMenuItem, Menu, NativeIcon, PredefinedMenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{AppHandle, Manager};

use crate::state::AppState;

/// Handles to tray items that mirror engine state, stored in AppState so
/// commands can enable/disable them as the engine phase changes.
#[derive(Clone)]
pub struct TrayState {
    pub start: IconMenuItem<tauri::Wry>,
    pub stop: IconMenuItem<tauri::Wry>,
    pub restart: IconMenuItem<tauri::Wry>,
}

/// Update tray item enablement from the current engine phase.
pub fn refresh(app: &AppHandle) {
    let st = app.state::<AppState>();
    let Some(items) = st.tray_state.lock().unwrap().clone() else {
        return;
    };
    let running = st.runtime.phase() != crate::runtime::PHASE_STOPPED;
    let _ = items.start.set_enabled(!running);
    let _ = items.stop.set_enabled(running);
    let _ = items.restart.set_enabled(running);
}

pub fn setup_tray(app: &AppHandle) -> tauri::Result<()> {
    let open = IconMenuItem::with_id_and_native_icon(
        app, "open", "Open Harness", true, Some(NativeIcon::Home), None::<&str>,
    )?;
    let settings = IconMenuItem::with_id_and_native_icon(
        app, "settings", "Control Panel…", true, Some(NativeIcon::PreferencesGeneral), None::<&str>,
    )?;
    let start = IconMenuItem::with_id_and_native_icon(
        app, "start", "Start Harness", false, Some(NativeIcon::RightFacingTriangle), None::<&str>,
    )?;
    let stop = IconMenuItem::with_id_and_native_icon(
        app, "stop", "Stop Harness", false, Some(NativeIcon::StopProgress), None::<&str>,
    )?;
    let restart = IconMenuItem::with_id_and_native_icon(
        app, "restart", "Restart Harness", false, Some(NativeIcon::Refresh), None::<&str>,
    )?;
    let browser = IconMenuItem::with_id_and_native_icon(
        app, "browser", "Open in Browser", true, Some(NativeIcon::FollowLinkFreestanding), None::<&str>,
    )?;
    let quit = IconMenuItem::with_id_and_native_icon(
        app, "quit", "Quit Harness Launcher", true, Some(NativeIcon::StopProgressFreestanding), None::<&str>,
    )?;
    let sep = PredefinedMenuItem::separator(app)?;
    let items: &[&dyn IsMenuItem<tauri::Wry>] = &[&open, &settings, &sep, &start, &stop, &restart, &sep, &browser, &sep, &quit];
    let menu = Menu::with_items(app, items)?;

    *app.state::<AppState>().tray_state.lock().unwrap() = Some(TrayState { start, stop, restart });

    // Logo-derived black glyphs render crisply in the macOS menu bar as a
    // template image (generated by scripts/gen-icons.mjs at prep time).
    let icon = tauri::image::Image::from_bytes(include_bytes!("../resources/tray/tray-icon.png")).ok();
    let mut builder = TrayIconBuilder::with_id("main")
        .tooltip("Harness Launcher")
        .menu(&menu)
        .icon_as_template(true);
    if let Some(icon) = icon {
        builder = builder.icon(icon);
    }

    builder
        .on_menu_event(|app, event| match event.id().as_ref() {
            "open" => {
                let _ = show_main_window(app);
            }
            "settings" => {
                let _ = crate::window::open_settings_window(app);
            }
            "start" => {
                let handle = app.clone();
                tauri::async_runtime::spawn(async move {
                    let _ = crate::commands::engine_start(handle).await;
                });
            }
            "stop" => {
                let handle = app.clone();
                tauri::async_runtime::spawn(async move {
                    let _ = crate::commands::engine_stop(handle);
                });
            }
            "restart" => {
                let handle = app.clone();
                tauri::async_runtime::spawn(async move {
                    let _ = crate::commands::engine_restart(handle).await;
                });
            }
            "browser" => {
                let _ = crate::commands::open_in_browser(app.clone());
            }
            "quit" => {
                let _ = crate::commands::quit_app(app.clone());
            }
            _ => {}
        })
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            } = event
            {
                let app = tray.app_handle();
                let _ = show_main_window(app);
            }
        })
        .build(app)?;
    Ok(())
}

pub fn show_main_window(app: &AppHandle) -> Result<(), String> {
    let running = app.state::<AppState>().runtime.is_running();
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.show();
        let _ = window.set_focus();
        if !running {
            let _ = crate::window::navigate(app, "dsh-ui://localhost/stopped");
        }
        return Ok(());
    }
    if running {
        crate::window::ensure_window(
            app,
            &crate::commands::harness_web_url(app, current_port(app), Some(std::time::Duration::from_secs(5))),
        )
    } else {
        crate::window::ensure_window(app, "dsh-ui://localhost/stopped")
    }
}

fn current_port(app: &AppHandle) -> u16 {
    *app.state::<AppState>().effective_port.lock().unwrap()
}