//! Tray icon + menu (macOS menu bar). The launcher runs menubar-only:
//! no Dock icon, window hides instead of closing, quit only from the tray.
//! Engine-related items reflect the live engine phase (refresh()).
//! Every item carries an SF Symbol glyph (template PNG generated by
//! scripts/gen-symbols.mjs, tinted by macOS via the patched muda), and the
//! menu intentionally omits force-restart / update-harness items — those are
//! covered by the Control Panel and engine card.
use tauri::image::Image;
use tauri::menu::{IconMenuItem, IsMenuItem, Menu, PredefinedMenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{AppHandle, Manager};

use crate::state::AppState;

/// Handles to tray items that mirror engine state, stored in AppState so
/// commands can enable/disable them as the engine phase changes.
#[derive(Clone)]
pub struct TrayState {
    pub start: IconMenuItem<tauri::Wry>,
    pub stop: IconMenuItem<tauri::Wry>,
    pub restart: IconMenuItem<tauri::Wry>,
    pub fullscreen_harness: IconMenuItem<tauri::Wry>,
    pub fullscreen_settings: IconMenuItem<tauri::Wry>,
}

/// Update tray item enablement from the current engine phase.
pub fn refresh(app: &AppHandle) {
    let st = app.state::<AppState>();
    let Some(items) = st.tray_state.lock().unwrap().clone() else {
        return;
    };
    let running = st.runtime.phase() != crate::runtime::PHASE_STOPPED;
    let _ = items.start.set_enabled(!running);
    let _ = items.stop.set_enabled(running);
    let _ = items.restart.set_enabled(running);
    // Fullscreen toggles act on live windows only: disable while the window
    // does not exist (the main window is created at boot when configured to
    // open on launch; the panel is created on demand).
    let _ = items
        .fullscreen_harness
        .set_enabled(app.get_webview_window(crate::window::LABEL).is_some());
    let _ = items
        .fullscreen_settings
        .set_enabled(app.get_webview_window(crate::window::SETTINGS_LABEL).is_some());
}

/// SF Symbol glyphs for the tray menu items, generated at prep time by
/// scripts/gen-symbols.mjs from the symbol mapping specified by the user.
/// Black+alpha PNGs at 18pt@2x, attached via Image (not NativeIcon) and
/// rendered as template images by the locally patched muda, so macOS tints
/// them monochrome per menu appearance (light/dark) automatically.
const SYM_OPEN: &[u8] = include_bytes!("../resources/tray/symbol/open.png");
const SYM_SETTINGS: &[u8] = include_bytes!("../resources/tray/symbol/settings.png");
const SYM_START: &[u8] = include_bytes!("../resources/tray/symbol/start.png");
const SYM_STOP: &[u8] = include_bytes!("../resources/tray/symbol/stop.png");
const SYM_RESTART: &[u8] = include_bytes!("../resources/tray/symbol/restart.png");
const SYM_BROWSER: &[u8] = include_bytes!("../resources/tray/symbol/browser.png");
const SYM_FULLSCREEN_HARNESS: &[u8] = include_bytes!("../resources/tray/symbol/fullscreen-harness.png");
const SYM_FULLSCREEN_SETTINGS: &[u8] = include_bytes!("../resources/tray/symbol/fullscreen-settings.png");
const SYM_QUIT: &[u8] = include_bytes!("../resources/tray/symbol/quit.png");

/// Menu item carrying the given SF Symbol glyph.
fn symbol_item(
    app: &AppHandle,
    id: &str,
    label: &str,
    enabled: bool,
    png: &'static [u8],
) -> tauri::Result<IconMenuItem<tauri::Wry>> {
    let image = Image::from_bytes(png)?;
    IconMenuItem::with_id(app, id, label, enabled, Some(image), None::<&str>)
}

pub fn setup_tray(app: &AppHandle) -> tauri::Result<()> {
    let open = symbol_item(app, "open", "Open Harness", true, SYM_OPEN)?;
    let settings = symbol_item(app, "settings", "Control Panel…", true, SYM_SETTINGS)?;
    let start = symbol_item(app, "start", "Start Harness", false, SYM_START)?;
    let stop = symbol_item(app, "stop", "Stop Harness", false, SYM_STOP)?;
    let restart = symbol_item(app, "restart", "Restart Harness", false, SYM_RESTART)?;
    let browser = symbol_item(app, "browser", "Open in Browser", true, SYM_BROWSER)?;
    let fullscreen_harness =
        symbol_item(app, "fullscreen-harness", "Harness Full Screen", false, SYM_FULLSCREEN_HARNESS)?;
    let fullscreen_settings = symbol_item(
        app,
        "fullscreen-settings",
        "Control Panel Full Screen",
        false,
        SYM_FULLSCREEN_SETTINGS,
    )?;
    let quit = symbol_item(app, "quit", "Quit Harness Launcher", true, SYM_QUIT)?;
    let sep = PredefinedMenuItem::separator(app)?;
    let sep2 = PredefinedMenuItem::separator(app)?;
    let items: &[&dyn IsMenuItem<tauri::Wry>] = &[&open, &settings, &sep, &start, &stop, &restart, &sep, &browser, &fullscreen_harness, &fullscreen_settings, &sep2, &quit];
    let menu = Menu::with_items(app, items)?;

    *app.state::<AppState>().tray_state.lock().unwrap() = Some(TrayState {
        start,
        stop,
        restart,
        fullscreen_harness,
        fullscreen_settings,
    });

    // Logo-derived black glyphs render crisply in the macOS menu bar as a
    // template image (generated by scripts/gen-icons.mjs at prep time).
    let icon = tauri::image::Image::from_bytes(include_bytes!("../resources/tray/tray-icon.png")).ok();
    let mut builder = TrayIconBuilder::with_id("main")
        .tooltip("Harness Launcher")
        .menu(&menu)
        .icon_as_template(true);
    if let Some(icon) = icon {
        builder = builder.icon(icon);
    }

    builder
        .on_menu_event(|app, event| match event.id().as_ref() {
            "open" => {
                let _ = show_main_window(app);
            }
            "settings" => {
                let _ = crate::window::open_settings_window(app);
            }
            "start" => {
                let handle = app.clone();
                tauri::async_runtime::spawn(async move {
                    let _ = crate::commands::engine_start(handle).await;
                });
            }
            "stop" => {
                let handle = app.clone();
                tauri::async_runtime::spawn(async move {
                    let _ = crate::commands::stop_engine_now(&handle);
                });
            }
            "restart" => {
                let handle = app.clone();
                tauri::async_runtime::spawn(async move {
                    let _ = crate::commands::restart_engine_now(handle).await;
                });
            }
            "browser" => {
                let _ = crate::commands::open_in_browser(app.clone());
            }
            "fullscreen-harness" => {
                toggle_fullscreen(app, crate::window::LABEL);
            }
            "fullscreen-settings" => {
                toggle_fullscreen(app, crate::window::SETTINGS_LABEL);
            }
            "quit" => {
                crate::commands::quit_app_now(app);
            }
            _ => {}
        })
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            } = event
            {
                let app = tray.app_handle();
                let _ = show_main_window(app);
            }
        })
        .build(app)?;
    Ok(())
}

/// Toggle native macOS fullscreen on a launcher window and focus it. A
/// missing window is a no-op — its tray item is disabled while it does not
/// exist (see refresh()), so this only fires for live windows.
fn toggle_fullscreen(app: &AppHandle, label: &str) {
    let Some(window) = app.get_webview_window(label) else {
        return;
    };
    if let Ok(fullscreen) = window.is_fullscreen() {
        let _ = window.set_fullscreen(!fullscreen);
        let _ = window.set_focus();
    }
}

pub fn show_main_window(app: &AppHandle) -> Result<(), String> {
    let running = app.state::<AppState>().runtime.is_running();
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.show();
        let _ = window.set_focus();
        if !running {
            let _ = crate::window::navigate(app, "dsh-ui://localhost/stopped");
        }
        return Ok(());
    }
    if running {
        crate::window::ensure_window(
            app,
            &crate::commands::harness_web_url(app, current_port(app), Some(std::time::Duration::from_secs(5))),
        )
    } else {
        crate::window::ensure_window(app, "dsh-ui://localhost/stopped")
    }
}

fn current_port(app: &AppHandle) -> u16 {
    *app.state::<AppState>().effective_port.lock().unwrap()
}